-- Daily report snapshots: the stored results of the price-dependent reports
-- (portfolio overview, unrealised gains, performance), one row per
-- (report, date), generated by the scheduled `report-snapshot` job once the
-- day's last close is in, or on demand for backfilled past dates.
--
-- A snapshot records the report as computed at generation time: the facts
-- recorded then, valued at the stored closing prices of `snapshot_date`
-- (AUD-converted). Recording a back-dated fact therefore makes every snapshot
-- dated on or after it untrustworthy — the triggers below set `stale` in the
-- same transaction as the fact write, so no write path (entity CRUD, Sells,
-- transfers, corporate-action operations, DRP reinvestment, …) can bypass it.
-- A stale snapshot keeps showing its stored result, visibly flagged, until it
-- is regenerated on demand. A day whose prices failed to fetch has no row at
-- all (missing, distinguishable from stale).

CREATE TABLE report_snapshots (
    report        TEXT NOT NULL CHECK (report IN
                      ('portfolio_overview', 'unrealised_gains', 'performance')),
    snapshot_date TEXT NOT NULL,
    -- RFC 3339 UTC timestamp of the run that produced this result.
    generated_at  TEXT NOT NULL,
    -- 1 = a back-dated fact was recorded after generation; the stored result
    -- no longer reflects the books and should be regenerated.
    stale         INTEGER NOT NULL DEFAULT 0 CHECK (stale IN (0, 1)),
    -- The report's response rows as JSON. Money fields inside are Decimal
    -- strings (the API's serialisation), kept in TEXT — never a REAL/float.
    rows_json     TEXT NOT NULL,
    PRIMARY KEY (report, snapshot_date)
);

-- ---------------------------------------------------------------------------
-- Staleness invalidation triggers: any insert/update/delete of a dated fact
-- marks every snapshot dated on or after that fact stale, atomically with the
-- fact itself. An update invalidates from the earlier of the old and new
-- dates (moving a trade from March back to January must stale January on).
-- Dates are ISO-8601 TEXT, so string comparison is date comparison.
-- ---------------------------------------------------------------------------

-- Trades (Buy/Sell/DRP — including the rows created by Sells, transfers,
-- DRP reinvestments, and corporate-action operations).
CREATE TRIGGER trades_stale_snapshots_insert AFTER INSERT ON trades
BEGIN
    UPDATE report_snapshots SET stale = 1 WHERE snapshot_date >= NEW.date;
END;
CREATE TRIGGER trades_stale_snapshots_update AFTER UPDATE ON trades
BEGIN
    UPDATE report_snapshots SET stale = 1
    WHERE snapshot_date >= MIN(OLD.date, NEW.date);
END;
CREATE TRIGGER trades_stale_snapshots_delete AFTER DELETE ON trades
BEGIN
    UPDATE report_snapshots SET stale = 1 WHERE snapshot_date >= OLD.date;
END;

-- Parcel allocations take effect on their sale trade's date. (If the sale
-- trade is deleted in the same transaction, its own trades trigger covers
-- the invalidation; the subquery then finds no row and updates nothing.)
CREATE TRIGGER parcel_allocations_stale_snapshots_insert AFTER INSERT ON parcel_allocations
BEGIN
    UPDATE report_snapshots SET stale = 1 WHERE snapshot_date >=
        (SELECT date FROM trades WHERE id = NEW.sale_trade_id);
END;
CREATE TRIGGER parcel_allocations_stale_snapshots_update AFTER UPDATE ON parcel_allocations
BEGIN
    UPDATE report_snapshots SET stale = 1 WHERE snapshot_date >=
        MIN((SELECT date FROM trades WHERE id = OLD.sale_trade_id),
            (SELECT date FROM trades WHERE id = NEW.sale_trade_id));
END;
CREATE TRIGGER parcel_allocations_stale_snapshots_delete AFTER DELETE ON parcel_allocations
BEGIN
    UPDATE report_snapshots SET stale = 1 WHERE snapshot_date >=
        (SELECT date FROM trades WHERE id = OLD.sale_trade_id);
END;

-- Income (performance cash flows) takes effect on the pay date.
CREATE TRIGGER income_stale_snapshots_insert AFTER INSERT ON income
BEGIN
    UPDATE report_snapshots SET stale = 1 WHERE snapshot_date >= NEW.date_paid;
END;
CREATE TRIGGER income_stale_snapshots_update AFTER UPDATE ON income
BEGIN
    UPDATE report_snapshots SET stale = 1
    WHERE snapshot_date >= MIN(OLD.date_paid, NEW.date_paid);
END;
CREATE TRIGGER income_stale_snapshots_delete AFTER DELETE ON income
BEGIN
    UPDATE report_snapshots SET stale = 1 WHERE snapshot_date >= OLD.date_paid;
END;

-- AMMA statements adjust cost bases for the year ending tax_year_end_date;
-- snapshots from that year end on see the adjustment.
CREATE TRIGGER amma_statements_stale_snapshots_insert AFTER INSERT ON amma_statements
BEGIN
    UPDATE report_snapshots SET stale = 1
    WHERE snapshot_date >= NEW.tax_year_end_date;
END;
CREATE TRIGGER amma_statements_stale_snapshots_update AFTER UPDATE ON amma_statements
BEGIN
    UPDATE report_snapshots SET stale = 1
    WHERE snapshot_date >= MIN(OLD.tax_year_end_date, NEW.tax_year_end_date);
END;
CREATE TRIGGER amma_statements_stale_snapshots_delete AFTER DELETE ON amma_statements
BEGIN
    UPDATE report_snapshots SET stale = 1
    WHERE snapshot_date >= OLD.tax_year_end_date;
END;

-- AMIT adjustments apply their statement's year-end date to specific parcels.
CREATE TRIGGER amit_adjustments_stale_snapshots_insert AFTER INSERT ON amit_adjustments
BEGIN
    UPDATE report_snapshots SET stale = 1 WHERE snapshot_date >=
        (SELECT tax_year_end_date FROM amma_statements WHERE id = NEW.amma_statement_id);
END;
CREATE TRIGGER amit_adjustments_stale_snapshots_update AFTER UPDATE ON amit_adjustments
BEGIN
    UPDATE report_snapshots SET stale = 1 WHERE snapshot_date >=
        MIN((SELECT tax_year_end_date FROM amma_statements WHERE id = OLD.amma_statement_id),
            (SELECT tax_year_end_date FROM amma_statements WHERE id = NEW.amma_statement_id));
END;
CREATE TRIGGER amit_adjustments_stale_snapshots_delete AFTER DELETE ON amit_adjustments
BEGIN
    UPDATE report_snapshots SET stale = 1 WHERE snapshot_date >=
        (SELECT tax_year_end_date FROM amma_statements WHERE id = OLD.amma_statement_id);
END;

-- Corporate actions (splits, returns of capital, …) take effect on their date.
CREATE TRIGGER corporate_actions_stale_snapshots_insert AFTER INSERT ON corporate_actions
BEGIN
    UPDATE report_snapshots SET stale = 1 WHERE snapshot_date >= NEW.date;
END;
CREATE TRIGGER corporate_actions_stale_snapshots_update AFTER UPDATE ON corporate_actions
BEGIN
    UPDATE report_snapshots SET stale = 1
    WHERE snapshot_date >= MIN(OLD.date, NEW.date);
END;
CREATE TRIGGER corporate_actions_stale_snapshots_delete AFTER DELETE ON corporate_actions
BEGIN
    UPDATE report_snapshots SET stale = 1 WHERE snapshot_date >= OLD.date;
END;

-- A revised closing price invalidates snapshots from its date too: a re-fetch
-- that replaces a price a snapshot was valued at (or errors it out) changes
-- the result. A fetch that merely fills a gap (insert, or error → ok) stales
-- nothing — generation refuses errored prices, so no stored snapshot used one.
CREATE TRIGGER closing_prices_stale_snapshots_update AFTER UPDATE ON closing_prices
WHEN OLD.status = 'ok' AND (NEW.status <> 'ok' OR OLD.price <> NEW.price)
BEGIN
    UPDATE report_snapshots SET stale = 1 WHERE snapshot_date >= OLD.price_date;
END;
